### ISSUE TITLE
Does not seem to work on kernel 6.2.8

### ISSUE THREAD

**Issue by EdLovecraft** [lexi-src/kernel-rdtsc-patch#1]
I have managed to create a patch and apply it and compile the kernel, but I see no difference, CPU frequency is the same as before, and no `[handle_rdtsc] fake rdtsc vmx function is working` in the dmesg

**Comment by lexi-src** [comment]
> I have managed to create a patch and apply it and compile the kernel, but I see no difference, CPU frequency is the same as before, and no `[handle_rdtsc] fake rdtsc vmx function is working` in the dmesg

Did you add this to your VM configuration?

```
<qemu:arg value="-cpu"/>
<qemu:arg value="host,rdtscp=off,-hypervisor"/>
```
