### ISSUE TITLE
Help with Compiling

### ISSUE THREAD

**Issue by Puppeteer-rg** [lexi-src/kernel-rdtsc-patch#2]
Hey I just need help with compiling this. I always get error 2. Been trying to find out why and still doesn't go away.

**Comment by lexi-src** [comment]
Hello Puppeteer-rg, I'll need a bit more information to help you debug this.

Which OS are you using?
Are you able to provide more of the error output?

**Comment by Puppeteer-rg** [comment]
I managed to get it working. I used pafish to test if it actually worked. Does this mean it worked?
![image](https://user-images.githubusercontent.com/74965367/235333448-b7dba6ff-6b6a-4bbd-83e0-3ba8d2034b43.png)

**Comment by lexi-src** [comment]
Are those the only traces that occurred?

**Comment by Puppeteer-rg** [comment]
Here are the pafish logs. 
``
[pafish] Start
[pafish] Windows version: 6.2 build 9200 (WoW64)
[pafish] CPU: GenuineIntel (HV: Microsoft Hv) 11th Gen Intel(R) Core(TM) i5-11260H @ 2.60GHz
[pafish] CPU VM traced by checking the difference between CPU timestamp counters (rdtsc) forcing VM exit
[pafish] CPU VM traced by checking cpuid hypervisor vendor for known VM vendors
[pafish] Sandbox traced by missing mouse movement
[pafish] Sandbox traced by missing mouse movement or supernatural speed
[pafish] Sandbox traced by missing mouse click activity
[pafish] Sandbox traced by missing double click activity
[pafish] Sandbox traced by missing dialog confirmation
[pafish] Sandbox traced by missing or implausible dialog confirmation
[pafish] Sandbox traced by checking operating system uptime using GetTickCount()
[pafish] Hooks traced using ShellExecuteExW method 1
[pafish] Qemu traced using Reg key HKLM\HARDWARE\DEVICEMAP\Scsi\Scsi Port 0\Scsi Bus 0\Target Id 0\Logical Unit Id 0 "Identifier"
[pafish] Bochs traced using Reg key HKLM\HARDWARE\Description\System "SystemBiosVersion"
[pafish] End
``

**Comment by lexi-src** [comment]
Please fix the format.

**Comment by Puppeteer-rg** [comment]
There. Edited the message.

**Comment by lexi-src** [comment]
Have you loaded the kernel on your host system?

**Comment by Puppeteer-rg** [comment]
Yes. After I installed the driver I did this command from [this link](https://github.com/WCharacter/RDTSC-KVM-Handler).

```sudo make INSTALL_MOD_STRIP=1 modules_install && sudo make install```

**Comment by lexi-src** [comment]
> uname -r

**Comment by Puppeteer-rg** [comment]
6.2.0-20-generic

**Comment by lexi-src** [comment]
I can't help you compile the kernel for your distro but I'm sure there's something out there that can.

**Comment by Puppeteer-rg** [comment]
Alright. Thanks.

**Comment by Puppeteer-rg** [comment]
Managed to compile and install the kernel. uname -a says that the kernel is custom.

Pafish still says rdtsc is being traced.
